# Generated by Django 3.1.5 on 2021-01-15 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('receives', '0002_auto_20210114_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 1, 15, 19, 32, 37, 975392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emailsthatwillreceive',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2021, 1, 15, 19, 32, 37, 976290, tzinfo=utc)),
        ),
    ]
